[core] Add grace period for core worker to initialize in IO worker (#50310)
`test_object_spilling_2` is flaky with the following traceback:
```
[2025-02-07T09:44:54Z] (raylet) 2025-02-07 09:42:55,425	ERROR (unknown file):0 -- An unexpected internal error occurred while the IO worker was spilling objects: 'Worker' object has no attribute 'core_worker'
[2025-02-07T09:44:54Z] (raylet) Traceback (most recent call last):
[2025-02-07T09:44:54Z] (raylet)   File "python/ray/_raylet.pyx", line 2419, in ray._raylet.spill_objects_handler
[2025-02-07T09:44:54Z] (raylet)   File "/rayci/python/ray/_private/external_storage.py", line 677, in spill_objects
[2025-02-07T09:44:54Z] (raylet)     return _external_storage.spill_objects(object_refs, owner_addresses)
[2025-02-07T09:44:54Z] (raylet)     return self._write_multiple_objects(f, object_refs, owner_addresses, url)
[2025-02-07T09:44:54Z] (raylet)   File "/rayci/python/ray/_private/external_storage.py", line 126, in _write_multiple_objects
[2025-02-07T09:44:54Z] (raylet)     ray_object_pairs = self._get_objects_from_store(object_refs)
[2025-02-07T09:44:54Z] (raylet)   File "/rayci/python/ray/_private/external_storage.py", line 96, in _get_objects_from_store
[2025-02-07T09:44:54Z] (raylet)     ray_object_pairs = worker.core_worker.get_if_local(object_refs)
[2025-02-07T09:44:54Z] (raylet) AttributeError: 'Worker' object has no attribute 'core_worker'
```

After investigation, it looks like this can happen because the
spill/restore work is initiated by the raylet and we don't have an
explicit barrier that indicates when the Python layer is ready to start
executing work. See:
https://github.com/ray-project/ray/blob/0e605ef34880b729b9ff147031fa2bb0c4e64866/python/ray/_private/workers/default_worker.py#L299

This PR addresses the issue by adding a grace period to check that the
core worker has been initialized. This is a workaround and we should fix
the initialization procedure in the near term.

I confirmed it fixes the flaky test issue by running the test 5x with
the change (all 5 passed).

---------

Signed-off-by: Edward Oakes <ed.nmi.oakes@gmail.com>